### PR TITLE
Add option "nginx_extra_log_formats" to setup multiple log formats

### PR DESCRIPTION
**Pull request by racke**
In case you need more than one log_format in your Nginx configuration.

### CODE REVIEW

**Comment by racke** [comment]
Ping.

**Review by Adirael — COMMENTED** [review]
I just tried this to add an extra log format to send logs to Graylog and it worked perfectly

**Review by simonspa — APPROVED** [review]

**Comment by simonspa** [comment]
It'd be great to get these changes in, @geerlingguy

**Comment by simonspa** [comment]
...it's ready to be merged!

**Comment by racke** [comment]
Ping.

**Pull request closed without merging**
