### PR TITLE
`server_tokens` is disabled by default

### PR DESCRIPTION
**Pull request by leventyalcin**
Actually, This setting can be changed by `nginx_extra_http_options`, but I think it's better to disable by default. If not, possibly, most of the people such as me will forget it

### CODE REVIEW

**Comment by geerlingguy** [comment]
It looks like another merged PR may have caused conflicts here. Can you rebase?

**Comment by bersace** [comment]
:up: :-)

**Comment by geerlingguy** [comment]
@leventyalcin - I'm okay adding in this variable, but unless it's an actual high-priority security fix, I stick to the defaults and allow them to be overridden. Nginx currently defaults to `on` (see http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens), so let's leave that as the default.

**Comment by bersace** [comment]
We customize `server_tokens` with extra. Merging this PR requires to update our vars to avoid emergency error.

``` console
$ grep -n server_tokens /etc/nginx/nginx.conf 
42:server_tokens off;
43:server_tokens off;
$ nginx -t
nginx: [emerg] "server_tokens" directive is duplicate in /etc/nginx/nginx.conf:43
nginx: configuration file /etc/nginx/nginx.conf test failed
$
```

Does it worth it ?

**Comment by leventyalcin** [comment]
@geerlingguy fair point. I'm always trying to avoid any mistake which can go to production and that was the reason why I've set it to `off` by default.

**Comment by geerlingguy** [comment]
Are you managing that configuration file by hand? I don't see how you'd get multiple `server_tokens` declarations in your configuration is this role is managing it...

**Comment by bersace** [comment]
@geerlingguy i can get twice server_tokens with:

```
nginx_server_tokens: off
nginx_extra_http_options: |
    server_tokens: off
```

Merging this PR will break such usage. I guess that it's common to set `server_tokens` with `extra_http_options`.

**Comment by geerlingguy** [comment]
@bersace - Ah, I see. So in that case, merging this will require at least a minor version bump so people know it's not just a small feature addition/bugfix.

**Comment by geerlingguy** [comment]
See https://github.com/geerlingguy/ansible-role-nginx/pull/82

**Pull request closed without merging**
