### PR TITLE
Issue #95: Add support for setting template on a per vhost basis

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by noplanman** [comment]
This is **exactly** what I imagined 😇

**Comment by geerlingguy** [comment]
This _rocks_. Kudos to @oxyc for the PR and @noplanman for the suggestion. Will tag a new release in a few minutes!

**Comment by noplanman** [comment]
@geerlingguy Brilliant, thanks so much! Now I can replace my homebrew role with yours everywhere 🎉 

(Keep this in mind for other roles, as it's super easy to implement and opens up to total flexibility.)

**Comment by geerlingguy** [comment]
> Keep this in mind for other roles

Yeah, I'm planning on adding this to a few others at least.

**Pull request merged**
