### PR TITLE
Don't start service in tasks. Defer to handlers to allow further configuration outside of role.

### PR DESCRIPTION
**Pull request by woneill**
Also clean up unused handler

### CODE REVIEW

**Comment by geerlingguy** [comment]
The `validate nginx configuration` is used in many downstream projects, so I'd like to leave that handler.

Also, rather than removing the `state=started` from the role itself, I have started using a pattern of having the service state be a variable (e.g. `nginx_service_state: started` in defaults/main.yml). This way people installing in a container or needing further control over the service state can set that variable (either in static vars or during runtime as needed) to control the service state more accurately.

So if you can undo the removal of the validate handler, and revert the change to the service task, but change the hardcoded `started` to `{{ nginx_service_state }}` (updating defaults/main.yml and README.md to reflect the changes), I'll merge this.

**Comment by woneill** [comment]
Thanks for the comments!

I've implemented your suggestions but also split out service state from service enablement so that I can skip setting `state` and let the handlers handle it. 

I did a rebase on this branch so let me know if you'd rather me do a new PR.

**Comment by bauen1** [comment]
@geerlingguy Does this have any chance of getting merged ? (The Travis Build seems to have simply stalled.)

**Comment by Jahsis** [comment]
@geerlingguy please, check this PR. This changes are useful.

**Comment by geerlingguy** [comment]
In the above commit, I removed a tiny bit of the flexibility your PR adds, but preserving at least the ability for this role to allow an initial state to be configured, or for the role to play nicely in an environment like Docker container builds, where you might not even have a service manager.

This is how I typically set up my other roles, but the Nginx one is old enough I never did this to it. Thanks!

**Comment by woneill** [comment]
Awesome seeing this revived!

I've since moved on to another job where we use Chef instead of Ansible but I'm happy to see this change get implemented :)

Thanks for some great Ansible work @geerlingguy. You saved me and my former team a _lot_ of work!

**Pull request merged**
